import { DEFAULT_CMS_CONTENT } from "@/lib/constants";

export type CmsFieldKey = keyof typeof DEFAULT_CMS_CONTENT;

export type CmsFieldConfig = {
  key: CmsFieldKey;
  label: string;
  kind?: "input" | "textarea" | "url" | "image";
  hint?: string;
};

export type CmsFieldSection = {
  title: string;
  description: string;
  fields: CmsFieldConfig[];
};

export const CMS_FIELD_SECTIONS: CmsFieldSection[] = [
  {
    title: "Topbar, links and brand",
    description: "Manage the top strip, shared contact links, social URLs, and brand tag.",
    fields: [
      { key: "topbarTagline", label: "Topbar tagline", kind: "textarea" },
      { key: "topbarSecondaryEmail", label: "Topbar secondary email" },
      { key: "topbarMapLabel", label: "Topbar map label" },
      { key: "topbarMapUrl", label: "Topbar map URL", kind: "url" },
      { key: "brandTag", label: "Brand tag line" },
      { key: "secondaryEmail", label: "Secondary email" },
      { key: "instagramUrl", label: "Instagram URL", kind: "url" },
      { key: "facebookUrl", label: "Facebook URL", kind: "url" },
      { key: "whatsappGroupUrl", label: "WhatsApp group URL", kind: "url" },
      { key: "embeddedMapUrl", label: "Embedded map URL", kind: "url" },
      { key: "emergencyCallLabel", label: "Emergency call button label" },
    ],
  },
  {
    title: "Hero menu",
    description: "Control the 10 top navigation labels and their dropdown item labels.",
    fields: [
      { key: "navAboutLabel", label: "About label" },
      { key: "navAboutItemOneLabel", label: "About item 1" },
      { key: "navAboutItemTwoLabel", label: "About item 2" },
      { key: "navWhyChooseLabel", label: "Why Choose Us label" },
      { key: "navWhyChooseItemOneLabel", label: "Why Choose item 1" },
      { key: "navWhyChooseItemTwoLabel", label: "Why Choose item 2" },
      { key: "navMissionLabel", label: "Mission label" },
      { key: "navMissionItemOneLabel", label: "Mission item 1" },
      { key: "navMissionItemTwoLabel", label: "Mission item 2" },
      { key: "navVisionLabel", label: "Vision label" },
      { key: "navVisionItemOneLabel", label: "Vision item 1" },
      { key: "navVisionItemTwoLabel", label: "Vision item 2" },
      { key: "navDepartmentsLabel", label: "Departments label" },
      { key: "navDepartmentsItemOneLabel", label: "Departments item 1" },
      { key: "navDepartmentsItemTwoLabel", label: "Departments item 2" },
      { key: "navDoctorsLabel", label: "Doctors label" },
      { key: "navDoctorsItemOneLabel", label: "Doctors item 1" },
      { key: "navDoctorsItemTwoLabel", label: "Doctors item 2" },
      { key: "navServicesLabel", label: "Services label" },
      { key: "navServicesItemOneLabel", label: "Services item 1" },
      { key: "navServicesPageLabel", label: "Services page link label" },
      { key: "navServicesItemTwoLabel", label: "Services item 2" },
      { key: "navServicesItemThreeLabel", label: "Services item 3" },
      { key: "navFacilitiesLabel", label: "Facilities label" },
      { key: "navFacilitiesItemOneLabel", label: "Facilities item 1" },
      { key: "navFacilitiesItemTwoLabel", label: "Facilities item 2" },
      { key: "navTreatmentsLabel", label: "Treatments label" },
      { key: "navTreatmentsItemOneLabel", label: "Treatments item 1" },
      { key: "navTreatmentsItemTwoLabel", label: "Treatments item 2" },
      { key: "navContactLabel", label: "Contact label" },
      { key: "navContactItemOneLabel", label: "Contact item 1" },
      { key: "navContactPageLabel", label: "Contact page link label" },
      { key: "navContactItemTwoLabel", label: "Contact item 2" },
      { key: "navContactItemThreeLabel", label: "Contact item 3" },
    ],
  },
  {
    title: "Hero content",
    description: "Edit hero copy, CTA labels, quick access panel, QR image, and stat copy.",
    fields: [
      { key: "heroEyebrow", label: "Hero eyebrow" },
      { key: "heroHeading", label: "Hero heading", kind: "textarea" },
      { key: "heroDescription", label: "Hero description", kind: "textarea" },
      { key: "heroPrimaryCtaLabel", label: "Primary CTA label" },
      { key: "heroSecondaryCtaLabel", label: "Secondary CTA label" },
      { key: "heroPanelEyebrow", label: "Hero panel eyebrow" },
      { key: "heroPanelHeading", label: "Hero panel heading", kind: "textarea" },
      { key: "heroFeatureOne", label: "Hero feature 1" },
      { key: "heroFeatureTwo", label: "Hero feature 2" },
      { key: "heroFeatureThree", label: "Hero feature 3" },
      { key: "heroLocationLabel", label: "Hero location label" },
      { key: "heroQrLabel", label: "Hero QR label" },
      { key: "heroQrText", label: "Hero QR text", kind: "textarea" },
      { key: "heroQrImageUrl", label: "Hero QR image URL", kind: "image" },
      { key: "heroStatOneTitle", label: "Hero stat 1 title" },
      { key: "heroStatOneText", label: "Hero stat 1 text" },
      { key: "heroStatTwoTitle", label: "Hero stat 2 title" },
      { key: "heroStatTwoText", label: "Hero stat 2 text" },
      { key: "heroStatThreeTitle", label: "Hero stat 3 title" },
      { key: "heroStatThreeText", label: "Hero stat 3 text" },
    ],
  },
  {
    title: "About, trust and departments",
    description: "Control the about block, clinic highlights, trust section, and departments heading copy.",
    fields: [
      { key: "aboutEyebrow", label: "About eyebrow" },
      { key: "aboutHeading", label: "About heading" },
      { key: "aboutDescription", label: "About description", kind: "textarea" },
      { key: "aboutParagraphTwo", label: "About paragraph 2", kind: "textarea" },
      { key: "aboutParagraphThree", label: "About paragraph 3", kind: "textarea" },
      { key: "aboutHighlightsTitle", label: "About highlights title" },
      { key: "aboutHighlightOneLabel", label: "Highlight 1 label" },
      { key: "aboutHighlightTwoTitle", label: "Highlight 2 title" },
      { key: "aboutHighlightTwoLabel", label: "Highlight 2 label" },
      { key: "aboutHighlightThreeTitle", label: "Highlight 3 title" },
      { key: "aboutHighlightThreeLabel", label: "Highlight 3 label" },
      { key: "aboutHighlightFourTitle", label: "Highlight 4 title" },
      { key: "aboutHighlightFourLabel", label: "Highlight 4 label" },
      { key: "trustEyebrow", label: "Trust eyebrow" },
      { key: "trustHeading", label: "Trust heading", kind: "textarea" },
      { key: "departmentsEyebrow", label: "Departments eyebrow" },
      { key: "departmentsHeading", label: "Departments heading", kind: "textarea" },
    ],
  },
  {
    title: "Why choose us, mission and vision",
    description: "Manage the proof and positioning sections that establish trust.",
    fields: [
      { key: "whyChooseEyebrow", label: "Why Choose eyebrow" },
      { key: "whyChooseHeading", label: "Why Choose heading" },
      { key: "whyChooseCardOneTitle", label: "Why Choose card 1 title" },
      { key: "whyChooseCardOneText", label: "Why Choose card 1 text", kind: "textarea" },
      { key: "whyChooseCardTwoTitle", label: "Why Choose card 2 title" },
      { key: "whyChooseCardTwoText", label: "Why Choose card 2 text", kind: "textarea" },
      { key: "whyChooseCardThreeTitle", label: "Why Choose card 3 title" },
      { key: "whyChooseCardThreeText", label: "Why Choose card 3 text", kind: "textarea" },
      { key: "missionEyebrow", label: "Mission eyebrow" },
      { key: "missionHeading", label: "Mission heading" },
      { key: "missionDescription", label: "Mission description", kind: "textarea" },
      { key: "missionExtra", label: "Mission extra paragraph", kind: "textarea" },
      { key: "visionEyebrow", label: "Vision eyebrow" },
      { key: "visionHeading", label: "Vision heading" },
      { key: "visionDescription", label: "Vision description", kind: "textarea" },
      { key: "visionExtra", label: "Vision extra paragraph", kind: "textarea" },
    ],
  },
  {
    title: "Healthcare, facilities and pharmacies",
    description: "Edit healthcare positioning, facilities heading, emergency strip, and pharmacy support copy.",
    fields: [
      { key: "healthcareEyebrow", label: "Healthcare eyebrow" },
      { key: "healthcareHeading", label: "Healthcare heading" },
      { key: "healthcareCardOneTitle", label: "Healthcare card 1 title" },
      { key: "healthcareCardOneText", label: "Healthcare card 1 text", kind: "textarea" },
      { key: "healthcareCardTwoTitle", label: "Healthcare card 2 title" },
      { key: "healthcareCardTwoText", label: "Healthcare card 2 text", kind: "textarea" },
      { key: "healthcareCardThreeTitle", label: "Healthcare card 3 title" },
      { key: "healthcareCardThreeText", label: "Healthcare card 3 text", kind: "textarea" },
      { key: "facilitiesEyebrow", label: "Facilities eyebrow" },
      { key: "facilitiesHeading", label: "Facilities heading" },
      { key: "emergencyEyebrow", label: "Emergency eyebrow" },
      { key: "emergencyHeading", label: "Emergency heading" },
      { key: "emergencyText", label: "Emergency description", kind: "textarea" },
      { key: "emergencySupportText", label: "Emergency support line" },
      { key: "pharmaciesEyebrow", label: "Pharmacies eyebrow" },
      { key: "pharmaciesHeading", label: "Pharmacies heading" },
      { key: "pharmacyCardOneTitle", label: "Pharmacy card 1 title" },
      { key: "pharmacyCardOneText", label: "Pharmacy card 1 text", kind: "textarea" },
      { key: "pharmacyCardTwoTitle", label: "Pharmacy card 2 title" },
      { key: "pharmacyCardTwoText", label: "Pharmacy card 2 text", kind: "textarea" },
      { key: "pharmacyCardThreeTitle", label: "Pharmacy card 3 title" },
      { key: "pharmacyCardThreeText", label: "Pharmacy card 3 text", kind: "textarea" },
    ],
  },
  {
    title: "Gallery, services, doctors, treatments and blog",
    description: "Manage the section labels and CTA copy for the main discovery areas.",
    fields: [
      { key: "galleryEyebrow", label: "Gallery eyebrow" },
      { key: "galleryHeading", label: "Gallery heading" },
      { key: "galleryButtonLabel", label: "Gallery button label" },
      { key: "insideCenterEyebrow", label: "Inside center eyebrow" },
      { key: "insideCenterHeading", label: "Inside center heading", kind: "textarea" },
      { key: "insideCenterNote", label: "Inside center note", kind: "textarea" },
      { key: "servicesEyebrow", label: "Services eyebrow" },
      { key: "servicesHeading", label: "Services heading" },
      { key: "servicesNote", label: "Services note", kind: "textarea" },
      { key: "servicesIntro", label: "Services intro", kind: "textarea" },
      { key: "servicesPageButtonLabel", label: "Services page button label" },
      { key: "doctorsEyebrow", label: "Doctors eyebrow" },
      { key: "doctorsHeading", label: "Doctors heading" },
      { key: "doctorGalleryEyebrow", label: "Doctors Gallery eyebrow" },
      { key: "doctorGalleryHeading", label: "Doctors Gallery heading" },
      { key: "treatmentsEyebrow", label: "Treatments eyebrow" },
      { key: "treatmentsHeading", label: "Treatments heading", kind: "textarea" },
      { key: "treatmentsButtonLabel", label: "Treatments button label" },
      { key: "blogEyebrow", label: "Blog eyebrow" },
      { key: "blogHeading", label: "Blog heading", kind: "textarea" },
      { key: "blogButtonLabel", label: "Blog button label" },
    ],
  },
  {
    title: "Reviews section",
    description: "Control reviews presentation and the visitor review form labels.",
    fields: [
      { key: "reviewsEyebrow", label: "Reviews eyebrow" },
      { key: "reviewsHeading", label: "Reviews heading" },
      { key: "reviewsSubtitle", label: "Reviews subtitle" },
      { key: "reviewsSummaryCopy", label: "Reviews summary copy", kind: "textarea" },
      { key: "reviewsLoadMoreLabel", label: "Load more button label" },
      { key: "reviewFormEyebrow", label: "Review form eyebrow" },
      { key: "reviewFormHeading", label: "Review form heading" },
      { key: "reviewNameLabel", label: "Review name label" },
      { key: "reviewNamePlaceholder", label: "Review name placeholder" },
      { key: "reviewRatingLabel", label: "Review rating label" },
      { key: "reviewMessageLabel", label: "Review message label" },
      { key: "reviewMessagePlaceholder", label: "Review message placeholder" },
      { key: "reviewFormHelperText", label: "Review helper text", kind: "textarea" },
      { key: "reviewSubmitLabel", label: "Review submit button label" },
    ],
  },
  {
    title: "Appointment section",
    description: "Edit the appointment section copy, field labels, placeholders, and button text.",
    fields: [
      { key: "appointmentEyebrow", label: "Appointment eyebrow" },
      { key: "appointmentHeading", label: "Appointment heading" },
      { key: "appointmentDescription", label: "Appointment description", kind: "textarea" },
      { key: "appointmentNameLabel", label: "Name label" },
      { key: "appointmentNamePlaceholder", label: "Name placeholder" },
      { key: "appointmentPhoneLabel", label: "Phone label" },
      { key: "appointmentPhonePlaceholder", label: "Phone placeholder" },
      { key: "appointmentDepartmentLabel", label: "Department label" },
      { key: "appointmentDepartmentPlaceholder", label: "Department placeholder" },
      { key: "appointmentDoctorLabel", label: "Doctor label" },
      { key: "appointmentDoctorPlaceholder", label: "Doctor placeholder" },
      { key: "appointmentDoctorHelper", label: "Doctor helper text", kind: "textarea" },
      { key: "appointmentDateLabel", label: "Date label" },
      { key: "appointmentDatePlaceholder", label: "Date placeholder" },
      { key: "appointmentTimeLabel", label: "Time label" },
      { key: "appointmentTimePlaceholder", label: "Time placeholder" },
      { key: "appointmentButtonLabel", label: "Appointment button label" },
    ],
  },
  {
    title: "Contact and footer",
    description: "Manage contact details, social title, CTA labels, timing copy, and footer labels.",
    fields: [
      { key: "contactEyebrow", label: "Contact eyebrow" },
      { key: "contactHeading", label: "Contact heading" },
      { key: "contactDescription", label: "Contact description", kind: "textarea" },
      { key: "contactPhone", label: "Contact phone" },
      { key: "contactEmail", label: "Contact email" },
      { key: "contactAddress", label: "Contact address", kind: "textarea" },
      { key: "contactSocialTitle", label: "Social title" },
      { key: "contactMapButtonLabel", label: "Map button label" },
      { key: "contactPageButtonLabel", label: "Contact page button label" },
      { key: "contactTimingsTitle", label: "Timings title" },
      { key: "contactTimingsText", label: "Timings text", kind: "textarea" },
      { key: "footerTagline", label: "Footer tagline" },
      { key: "footerHighlightLabel", label: "Footer highlight label" },
      { key: "footerHighlightDescription", label: "Footer highlight description", kind: "textarea" },
      { key: "footerHomeLabel", label: "Footer home label" },
      { key: "footerDepartmentsLabel", label: "Footer departments label" },
      { key: "footerDoctorsLabel", label: "Footer doctors label" },
      { key: "footerAppointmentLabel", label: "Footer appointment label" },
      { key: "footerContactLabel", label: "Footer contact label" },
      { key: "footerTreatmentsLabel", label: "Footer treatments label" },
      { key: "footerBlogLabel", label: "Footer blog label" },
      { key: "footerGalleryLabel", label: "Footer gallery label" },
    ],
  },
];
