import type { MediaItem } from "@/types";

export const DEFAULT_MEDIA_ITEMS: Omit<MediaItem, "id" | "createdAt" | "updatedAt">[] = [
  {
    title: "Trusted diagnostics for Sainthia and Birbhum",
    caption: "Accurate diagnostics, specialist support, and patient-focused care under one roof.",
    alt: "Banerjee Diagnostic Foundation and Hospaccx front building view",
    imageUrl: "/images/dignostic center front in day.jpg",
    section: "hero",
    category: "Hero",
    ctaLabel: "Book Appointment",
    ctaLink: "#appointment",
    order: 1,
  },
  {
    title: "Warm reception and smooth patient support",
    caption: "Designed to keep registration, guidance, and diagnostics easy for every patient.",
    alt: "Reception desk inside Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/reception.jpg",
    section: "hero",
    category: "Hero",
    ctaLabel: "Explore Sections",
    ctaLink: "#services",
    order: 2,
  },
  {
    title: "Modern diagnostic environment",
    caption: "Structured diagnostic spaces that support cleaner workflows and faster patient assistance.",
    alt: "Diagnostic care environment at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/WhatsApp Image 2026-03-15 at 6.57.54 PM.jpeg",
    section: "hero",
    category: "Hero",
    ctaLabel: "View Gallery",
    ctaLink: "#gallery",
    order: 3,
  },
  {
    title: "Lab & Diagnostics",
    caption: "Reliable diagnostic spaces designed for careful testing, reporting, and clinical workflow support.",
    alt: "Diagnostic laboratory environment at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/WhatsApp Image 2026-03-15 at 6.57.54 PM (1).jpeg",
    section: "highlights",
    category: "Lab",
    order: 1,
  },
  {
    title: "Doctors & Specialist Support",
    caption: "Experienced consultants and specialist guidance available through structured OPD scheduling.",
    alt: "Doctor poster at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/sumit jain sethiya.jpeg",
    section: "highlights",
    category: "Doctors",
    order: 2,
  },
  {
    title: "Reception & Patient Helpdesk",
    caption: "Clean reception and assistance desk focused on patient comfort, scheduling, and front-desk support.",
    alt: "Reception and patient assistance area at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/reception (2).jpg",
    section: "highlights",
    category: "Reception",
    order: 3,
  },
  {
    title: "Specialist Doctors",
    caption: "Consultant poster display highlighting specialist availability and hospital branding.",
    alt: "Doctor poster display at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/nirmita saha.jpeg",
    section: "gallery",
    category: "Doctors",
    order: 1,
  },
  {
    title: "Orthopedic Specialist",
    caption: "Professional doctor poster integrated into the doctors gallery.",
    alt: "Orthopedic doctor poster at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/sumit jain sethiya.jpeg",
    section: "gallery",
    category: "Doctors",
    order: 2,
  },
  {
    title: "Hospital Reception",
    caption: "Patient reception and support desk with a clean and organized environment.",
    alt: "Reception area at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/reception.jpg",
    section: "gallery",
    category: "Infrastructure",
    order: 3,
  },
  {
    title: "Hospital Front View",
    caption: "Exterior building view of Banerjee Diagnostic Foundation and Hospaccx.",
    alt: "Front building view of Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/hospital-front.jpg",
    section: "gallery",
    category: "Infrastructure",
    ctaLabel: "Open Location",
    ctaLink: "https://www.google.com/maps/place/Hospaccx+(A+Unit+Of+Banerjee+Diagnostic+Foundation),+RK+Rd,+Sainthia,+West+Bengal+731234/@23.948436,87.682399,17z/data=!3m1!4b1!4m2!3m1!1s0x39f9fab7412804a7:0x7be0f90f62d5e994",
    order: 4,
  },
  {
    title: "Diagnostic Workflow",
    caption: "Clinical workflow spaces built to support testing, reporting, and patient follow-up.",
    alt: "Diagnostic workflow area at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/WhatsApp Image 2026-03-15 at 6.57.54 PM (2).jpeg",
    section: "gallery",
    category: "Reports",
    order: 5,
  },
  {
    title: "Reporting Support Area",
    caption: "Patient-focused support spaces tied to diagnostics and report delivery processes.",
    alt: "Diagnostic support area at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/WhatsApp Image 2026-03-15 at 6.57.54 PM.jpeg",
    section: "gallery",
    category: "Reports",
    order: 6,
  },
  {
    title: "Medical Excellence",
    caption: "Advanced diagnostic equipment and specialist-led care designed to keep reporting reliable and patient guidance clear.",
    alt: "Diagnostic care support at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/WhatsApp Image 2026-03-15 at 6.57.54 PM (1).jpeg",
    section: "whyChoose",
    category: "Why Choose Us",
    order: 1,
  },
  {
    title: "Patient-Centered Care",
    caption: "A clean, reassuring patient environment supported by coordinated staff and structured assistance.",
    alt: "Reception and patient support environment at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/reception.jpg",
    section: "whyChoose",
    category: "Why Choose Us",
    order: 2,
  },
  {
    title: "Community Trust",
    caption: "Accessible healthcare built around trust, compassionate support, and practical patient convenience.",
    alt: "Front building view of Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/dignostic center front in day.jpg",
    section: "whyChoose",
    category: "Why Choose Us",
    order: 3,
  },
  {
    title: "Integrated Care",
    caption: "Diagnostic services, specialist care, and care navigation coordinated through one healthcare ecosystem.",
    alt: "Hospital care infrastructure at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/hospital-front.jpg",
    section: "healthcare",
    category: "Complete Healthcare",
    order: 1,
  },
  {
    title: "Emergency & ICU",
    caption: "Emergency and ICU readiness supported by organized spaces and patient-first medical response planning.",
    alt: "Emergency and ICU support environment at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/WhatsApp Image 2026-03-15 at 6.57.54 PM (2).jpeg",
    section: "healthcare",
    category: "Complete Healthcare",
    order: 2,
  },
  {
    title: "Cashless Support",
    caption: "Supportive front-desk and care coordination for eligible card and payment assistance workflows.",
    alt: "Patient support area at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/reception (2).jpg",
    section: "healthcare",
    category: "Complete Healthcare",
    order: 3,
  },
  {
    title: "Vivekananda Ausadhalaya",
    caption: "Pharmacy access aligned with hospital diagnostics and patient convenience.",
    alt: "Pharmacy support visual for Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/dignostic center front.jpg",
    section: "pharmacies",
    category: "Pharmacy",
    order: 1,
  },
  {
    title: "Hospaccx Medicine",
    caption: "Supportive medicine access designed for continuity of care and easier patient follow-up.",
    alt: "Medicine support visual for Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/reception.jpg",
    section: "pharmacies",
    category: "Pharmacy",
    order: 2,
  },
  {
    title: "Patient-Focused Assistance",
    caption: "Guidance-driven pharmacy coordination that supports diagnosis, treatment, and recovery.",
    alt: "Patient assistance area at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/reception (2).jpg",
    section: "pharmacies",
    category: "Pharmacy",
    order: 3,
  },
  {
    title: "Clinical Biochemistry",
    caption: "Laboratory support for clearer metabolic, organ-function, and overall health evaluation.",
    alt: "Clinical biochemistry service visual at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/WhatsApp Image 2026-03-15 at 6.57.54 PM (1).jpeg",
    section: "services",
    category: "Laboratory",
    order: 1,
  },
  {
    title: "Clinical Haematology",
    caption: "Blood-focused laboratory support for ongoing clinical evaluation and reporting.",
    alt: "Clinical haematology visual at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/WhatsApp Image 2026-03-15 at 6.57.54 PM (2).jpeg",
    section: "services",
    category: "Laboratory",
    order: 2,
  },
  {
    title: "Clinical Pathology",
    caption: "Routine sample evaluation with patient-friendly reporting support.",
    alt: "Clinical pathology visual at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/WhatsApp Image 2026-03-15 at 6.57.54 PM.jpeg",
    section: "services",
    category: "Laboratory",
    order: 3,
  },
  {
    title: "Histopathology / FNAC",
    caption: "Tissue and cellular review supported by accurate lab workflow and reporting care.",
    alt: "Histopathology visual at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/hospital-front.jpg",
    section: "services",
    category: "Laboratory",
    order: 4,
  },
  {
    title: "Hormone Testing",
    caption: "Hormone and endocrine testing support guided through careful sample handling.",
    alt: "Hormone testing visual at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/reception.jpg",
    section: "services",
    category: "Laboratory",
    order: 5,
  },
  {
    title: "Microbiology",
    caption: "Focused infection and organism-based testing support for clinical planning.",
    alt: "Microbiology service visual at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/dignostic center front in day.jpg",
    section: "services",
    category: "Laboratory",
    order: 6,
  },
  {
    title: "Serology & Immunology",
    caption: "Immune-response and marker-based laboratory support designed for clearer diagnosis.",
    alt: "Serology and immunology service visual at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/reception (2).jpg",
    section: "services",
    category: "Laboratory",
    order: 7,
  },
  {
    title: "Doctor Information Background",
    caption: "Professional doctor-information backdrop used behind the doctor directory section.",
    alt: "Doctor information background at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/reception.jpg",
    section: "doctorsOverlay",
    category: "Doctors",
    order: 1,
  },
];
