import type { MediaItem } from "@/types";

export const DEFAULT_MEDIA_ITEMS: Omit<MediaItem, "id" | "createdAt" | "updatedAt">[] = [
  {
    title: "Trusted diagnostics for Sainthia and Birbhum",
    caption: "Accurate diagnostics, specialist support, and patient-focused care under one roof.",
    alt: "Banerjee Diagnostic Foundation and Hospaccx front building view",
    imageUrl: "/images/dignostic center front in day.jpg",
    section: "hero",
    category: "Hero",
    ctaLabel: "Book Appointment",
    ctaLink: "#appointment",
    order: 1,
  },
  {
    title: "Warm reception and smooth patient support",
    caption: "Designed to keep registration, guidance, and diagnostics easy for every patient.",
    alt: "Reception desk inside Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/reception.jpg",
    section: "hero",
    category: "Hero",
    ctaLabel: "Explore Sections",
    ctaLink: "#services",
    order: 2,
  },
  {
    title: "Modern diagnostic environment",
    caption: "Structured diagnostic spaces that support cleaner workflows and faster patient assistance.",
    alt: "Diagnostic care environment at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/WhatsApp Image 2026-03-15 at 6.57.54 PM.jpeg",
    section: "hero",
    category: "Hero",
    ctaLabel: "View Gallery",
    ctaLink: "#gallery",
    order: 3,
  },
  {
    title: "Lab & Diagnostics",
    caption: "Reliable diagnostic spaces designed for careful testing, reporting, and clinical workflow support.",
    alt: "Diagnostic laboratory environment at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/WhatsApp Image 2026-03-15 at 6.57.54 PM (1).jpeg",
    section: "highlights",
    category: "Lab",
    order: 1,
  },
  {
    title: "Doctors & Specialist Support",
    caption: "Experienced consultants and specialist guidance available through structured OPD scheduling.",
    alt: "Doctor poster at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/sumit jain sethiya.jpeg",
    section: "highlights",
    category: "Doctors",
    order: 2,
  },
  {
    title: "Reception & Patient Helpdesk",
    caption: "Clean reception and assistance desk focused on patient comfort, scheduling, and front-desk support.",
    alt: "Reception and patient assistance area at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/reception (2).jpg",
    section: "highlights",
    category: "Reception",
    order: 3,
  },
  {
    title: "Specialist Doctors",
    caption: "Consultant poster display highlighting specialist availability and hospital branding.",
    alt: "Doctor poster display at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/nirmita saha.jpeg",
    section: "gallery",
    category: "Doctors",
    order: 1,
  },
  {
    title: "Orthopedic Specialist",
    caption: "Professional doctor poster integrated into the doctors gallery.",
    alt: "Orthopedic doctor poster at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/sumit jain sethiya.jpeg",
    section: "gallery",
    category: "Doctors",
    order: 2,
  },
  {
    title: "Hospital Reception",
    caption: "Patient reception and support desk with a clean and organized environment.",
    alt: "Reception area at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/reception.jpg",
    section: "gallery",
    category: "Infrastructure",
    order: 3,
  },
  {
    title: "Hospital Front View",
    caption: "Exterior building view of Banerjee Diagnostic Foundation and Hospaccx.",
    alt: "Front building view of Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/hospital-front.jpg",
    section: "gallery",
    category: "Infrastructure",
    ctaLabel: "Open Location",
    ctaLink: "https://www.google.com/maps/place/Hospaccx+(A+Unit+Of+Banerjee+Diagnostic+Foundation),+RK+Rd,+Sainthia,+West+Bengal+731234/@23.948436,87.682399,17z/data=!3m1!4b1!4m2!3m1!1s0x39f9fab7412804a7:0x7be0f90f62d5e994",
    order: 4,
  },
  {
    title: "Diagnostic Workflow",
    caption: "Clinical workflow spaces built to support testing, reporting, and patient follow-up.",
    alt: "Diagnostic workflow area at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/WhatsApp Image 2026-03-15 at 6.57.54 PM (2).jpeg",
    section: "gallery",
    category: "Reports",
    order: 5,
  },
  {
    title: "Reporting Support Area",
    caption: "Patient-focused support spaces tied to diagnostics and report delivery processes.",
    alt: "Diagnostic support area at Banerjee Diagnostic Foundation and Hospaccx",
    imageUrl: "/images/WhatsApp Image 2026-03-15 at 6.57.54 PM.jpeg",
    section: "gallery",
    category: "Reports",
    order: 6,
  },
];
